@echo off
rem ===== IMEIndicator portable build script (MSVC x64) =====
rem ASCII only (cmd.exe reads .bat as ANSI).
setlocal

call "%~dp0build_env.bat"
if errorlevel 1 exit /b 1

if not exist "bin" mkdir bin

rem ===== Version = build date (auto-generated, only rewritten when changed) =====
rem src\version.h is consumed by src\ime.rc (VERSIONINFO) and src\main.c
rem (tray tooltip / startup log). Same-day rebuilds keep the file untouched so
rem incremental compilation stays effective.
set "VERFILE=src\version.h"
for /f %%i in ('powershell -NoProfile -Command "Get-Date -Format yyyy.MM.dd"') do set "VERSTR=%%i"
for /f "tokens=1-3 delims=." %%a in ("%VERSTR%") do (
    set "VY=%%a"
    set "VM=%%b"
    set "VD=%%c"
)
rem Leading-zero month/day would parse as octal in set /a; 1VM %% 100 strips it.
set /a VMN=1%VM% %% 100
set /a VDN=1%VD% %% 100
> "%VERFILE%.new" echo /* Auto-generated by build scripts - do not edit. */
>> "%VERFILE%.new" echo /* Version = build date. Regenerated only when the date changes. */
>> "%VERFILE%.new" echo #define IME_VER_YEAR %VY%
>> "%VERFILE%.new" echo #define IME_VER_MONTH %VMN%
>> "%VERFILE%.new" echo #define IME_VER_DAY %VDN%
>> "%VERFILE%.new" echo #define IME_VER_A "%VERSTR%"
>> "%VERFILE%.new" echo #define IME_VER_W L"%VERSTR%"
fc /b "%VERFILE%.new" "%VERFILE%" >nul 2>&1
if errorlevel 1 (
    move /y "%VERFILE%.new" "%VERFILE%" >nul
) else (
    del "%VERFILE%.new"
)

rc /nologo /fo bin\ime.res src\ime.rc
if errorlevel 1 (
    echo [ERROR] rc failed
    exit /b 1
)

rem /W4: warn clean. /Brepro: reproducible build. /TP: compile as C++ so the
rem COM / UIAutomation calls (p->Method()) compile without CINTERFACE macros.
cl /nologo /O2 /W4 /MT /utf-8 /DUNICODE /D_UNICODE /Brepro /TP /Isrc ^
   /Fobin\ ^
   src\main.c src\config.c src\ime.c src\caret.c src\overlay.c src\debug.c ^
   /link /OUT:bin/IMEIndicator.exe ^
   bin\ime.res ^
   user32.lib gdi32.lib shell32.lib ole32.lib oleaut32.lib imm32.lib oleacc.lib comctl32.lib advapi32.lib ^
   /SUBSYSTEM:WINDOWS

if errorlevel 1 (
    echo [ERROR] build failed
    exit /b 1
)

for %%F in (bin\IMEIndicator.exe) do echo [OK] bin/IMEIndicator.exe built. size=%%~zF bytes